"""empty message

Revision ID: 225ef32f94f8
Revises: 82f70d037ea0
Create Date: 2026-01-12 19:57:23.658360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225ef32f94f8'
down_revision = '82f70d037ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
